---
title: "Techniczne podsumowanie marca"
subtitle: "Globalne zawirowania z wpływem na polski rynek"
author: "Tomasz Szczerbicki"
date: 2026-04-04
categories: [Analiza techniczna, GPW, WIG, WIG20, mWIG40, sWIG80, podsumowanie miesięczne]
execute:
  echo: false
  warning: false
  message: false
  freeze: auto
toc: True
---

Zapraszam na podsumowanie marca na Giełdzie Papierów Wartościowych, a więc miesiąca spodziewanego spowolnienia, przekształconego w miesiąc spadków przez sytuację na Bliskim Wschodzie.

Z kwestii techniczno-organizacyjnych, na wstępie chciałbym wspomnieć o marcowych rewizjach indeksów GPW, w skutek których doszło do kilku roszad:

-   WIG20:

    -   IN: Tauron

    -   OUT: Orange

-   mWIG40:

    -   IN: Creotech, Orange, Polimex

    -   OUT: 11BIT, Huuuge, Tauron

-   sWIG80:

    -   IN: 11BIT, Answear, Huuuge, Medinice, Zremb

    -   OUT: Creotech, MCR, ML System, Polimex, XTPL

Dodatkowo w trakcie miesiąca z uwagi na kwestie regulacyjne indeks WIG opuściły dwie spółki: Atlantis oraz Lsisoft.

Zestawienie największych wzostów i spadków na GPW w marcu:

```{python}
import pandas as pd
import numpy as np
import yfinance as yf
import talib
import matplotlib.pyplot as plt
import seaborn as sns

analyzed_month = '2026-03-01'

plt.style.use('/Users/tomasz/Desktop/quarto2/styles/blog_style.mplstyle')

# funkcje
def wtd(df: pd.DataFrame):
    d1 = df.copy()
    weekly_close = d1['Close'].resample('W-FRI').last().shift()
    d1['weekly_close'] = weekly_close.reindex(d1.index, method = 'bfill')
    d1['WTD_%'] = (d1['Close'] / d1['weekly_close'] - 1) * 100
    return d1['WTD_%'].astype(float).round(4)

def mtd(df: pd.DataFrame):
    d1 = df.copy()
    month_map = dict(d1['Close'].groupby([d1.index.year, d1.index.month]).last())
    d1['prev_month_close'] = [month_map.get((d.year if d.month > 1 else d.year - 1,12 if d.month == 1 else d.month - 1), np.nan) for d in d1.index]
    d1['MTD_%'] = (d1['Close'] / d1['prev_month_close'] - 1) * 100
    return d1['MTD_%'].astype(float).round(4)

def ytd(df: pd.DataFrame):
    d1 = df.copy()
    year_map = dict(d1['Close'].groupby([d1.index.year]).last())
    d1['prev_year_close'] = [year_map.get(d.year -1 , np.nan) for d in d1.index]
    d1['YTD_%'] = (d1['Close'] / d1['prev_year_close'] - 1) * 100
    return d1['YTD_%'].astype(float).round(4)

def ATR(df: pd.DataFrame, n = 14):
    d1 = df.copy()
    d1['H-L'] = d1['High'] - d1['Low']
    d1['H-PC'] = d1['High'] - d1['Close'].shift(1)
    d1['L-PC'] = d1['Low'] - d1['Close'].shift(1)
    d1['TR'] = d1[['H-L', 'H-PC', 'L-PC']].max(axis = 1)
    d1['ATR'] = d1['TR'].ewm(span = n, min_periods = n).mean()
    return d1['ATR']

def supertrend(df: pd.DataFrame, atr_multiplier=3, atr_length = 15):
    d1 = df.copy()
    current_average_high_low = (d1['High']+d1['Low'])/2
    d1['atr'] = talib.ATR(d1['High'], d1['Low'], d1['Close'], timeperiod= atr_length)
    d1.dropna(inplace=True)

    d1['basicUpperband'] = current_average_high_low + (atr_multiplier * d1['atr'])
    d1['basicLowerband'] = current_average_high_low - (atr_multiplier * d1['atr'])
    first_upperBand_value = d1['basicUpperband'].iloc[0]
    first_lowerBand_value = d1['basicLowerband'].iloc[0]
    upperBand = [first_upperBand_value]
    lowerBand = [first_lowerBand_value]

    for i in range(1, len(d1)):
        if d1['basicUpperband'].iloc[i] < upperBand[i-1] or d1['Close'].iloc[i-1] > upperBand[i-1]:
            upperBand.append(d1['basicUpperband'].iloc[i])
        else:
            upperBand.append(upperBand[i-1])

        if d1['basicLowerband'].iloc[i] > lowerBand[i-1] or d1['Close'].iloc[i-1] < lowerBand[i-1]:
            lowerBand.append(d1['basicLowerband'].iloc[i])
        else:
            lowerBand.append(lowerBand[i-1])

    d1['upperband'] = upperBand
    d1['lowerband'] = lowerBand

    d1['has_crossed_upper'] = np.where((d1['Close'].shift(1) < d1['upperband'].shift(1)) & (d1['Close'] >= d1['upperband']), 1,0)
    d1['has_crossed_lower'] = np.where((d1['Close'].shift(1) > d1['lowerband'].shift(1)) & (d1['Close'] <= d1['lowerband']), 1,0)
    
    supertrend = ['upperband']
    for i in range(1, len(d1)):
        if d1['has_crossed_upper'].iloc[i] == 1:
            supertrend.append('lowerband')
        elif d1['has_crossed_lower'].iloc[i] == 1:
            supertrend.append('upperband')
        else:
            supertrend.append(supertrend[i-1])  # poprzednia wartość

    d1['supertrend_label'] = supertrend
    d1['supertrend'] = np.where(d1['supertrend_label'] == 'upperband', d1['upperband'], d1['lowerband'])
    d1.drop(['basicUpperband', 'basicLowerband'], axis=1, inplace=True)
    return d1[['supertrend_label', 'supertrend']]

def drawdown(df: pd.DataFrame):
    d1 = df.copy()
    d1['return'] = d1['Close'].pct_change()
    d1['cum_return'] = (1+ d1['return']).groupby(d1.index.year).cumprod()
    d1['cum_roll_max'] = d1['cum_return'].groupby(d1.index.year).cummax()
    d1['drawdown'] = d1['cum_roll_max'] - d1['cum_return']
    d1['drawdown_pct'] = d1['drawdown'] / d1['cum_roll_max'] * 100
    return d1['drawdown_pct'].astype(float).round(4)

def run_up(df: pd.DataFrame):
    d1 = df.copy()
    d1['return'] = d1['Close'].pct_change()
    d1['cum_return'] = (1+ d1['return']).groupby(d1.index.year).cumprod()
    d1['cum_roll_min'] = d1['cum_return'].groupby(d1.index.year).cummin()
    d1['run_up'] = d1['cum_return'] - d1['cum_roll_min']
    d1['run_up_pct'] = d1['run_up'] / d1['cum_roll_min'] * 100
    return d1['run_up_pct'].astype(float).round(4)

# wgranie słownika

dictionary_stocks = pd.read_excel('/Users/tomasz/Desktop/quarto2/shared_files/spolki_20260401.xlsx', index_col = 0)

dictionary_stocks['L1_nazwa'] = dictionary_stocks.L1_nazwa.replace('Produkcja przemysłowa i budowlano-montażowa', 'Prod. przem. i bud-montaż.')
```

```{python}
# starter code
stocks = dictionary_stocks[dictionary_stocks['in_WIG'] == True].ticker_yf.to_list()
ohlcv_data = {}

for ticker in stocks:
    temp = yf.download(ticker, start = '2024-01-01', interval = '1d')
    temp.dropna(how = 'any', inplace = True)

    ohlcv_data[ticker] = temp
    ohlcv_data[ticker].columns = ['Close', 'High', 'Low', 'Open', 'Volume']
    ohlcv_data[ticker]['ticker'] = ticker

    #yahoo finance ma błąd w danych dla MOL za okres 30.12.2024 - 10.06.2025. W to miejsce wstawiam dane stooq
    if ticker == 'MOL.WA':
        l1 = pd.read_csv('/Users/tomasz/Desktop/quarto2/shared_files/t1.csv')['Close'].to_list()
        ohlcv_data['MOL.WA'].loc[ '2024-12-30':'2025-06-10', 'Close'] = l1
    
    # podobnie błąd dla Dadelo w jednym dniu
    if ticker == 'DAD.WA':
        ohlcv_data['DAD.WA'].loc['2025-04-25', 'Close'] = 28.30

    # błąd dla CPD
    if ticker == 'CPD.WA':
        ohlcv_data['CPD.WA'].loc['2026-03-23':'2026-03-27', 'Close'] = [2, 1.885, 1.945, 1.945, 1.82]

    ohlcv_data[ticker]['pct_change'] = round(ohlcv_data[ticker]['Close'].pct_change() * 100,4)
    ohlcv_data[ticker]['WTD_pct'] = wtd(ohlcv_data[ticker])
    ohlcv_data[ticker]['MTD_pct'] = mtd(ohlcv_data[ticker])
    ohlcv_data[ticker]['YTD_pct'] = ytd(ohlcv_data[ticker])

    ohlcv_data[ticker]['yearly_drawdown_pct'] = drawdown(ohlcv_data[ticker])
    ohlcv_data[ticker]['yearly_run_up_pct'] = run_up(ohlcv_data[ticker])

    ohlcv_data[ticker]['Volume_to_SMA10'] = ohlcv_data[ticker]['Volume'].rolling(10).mean()
    ohlcv_data[ticker]['Volume_to_Vol_SMA10_pct'] = round((ohlcv_data[ticker]['Volume'] / ohlcv_data[ticker]['Volume'].rolling(10).mean() - 1) * 100,2)

    for i in [50,100,200,300]:
        l1 = ohlcv_data[ticker]['Close'].rolling(i).max()
        ohlcv_data[ticker][f'is_{i}_max'] = ohlcv_data[ticker]['Close'] == l1
        ohlcv_data[ticker][f'max_{i}_pct_distance'] = (ohlcv_data[ticker]['Close'] /  l1 - 1) * 100

    for i in [10, 20, 50,100,200]:
        ohlcv_data[ticker][f'SMA_{i}'] = ohlcv_data[ticker]['Close'].rolling(i).mean()
        ohlcv_data[ticker][f'is_above_SMA_{i}'] = ohlcv_data[ticker]['Close'] > ohlcv_data[ticker][f'SMA_{i}']
        ohlcv_data[ticker][f'has_crossed_SMA_{i}'] = np.where((ohlcv_data[ticker][f'is_above_SMA_{i}'] == True) & (ohlcv_data[ticker][f'is_above_SMA_{i}'].shift() == False), 'up',
                                                            np.where((ohlcv_data[ticker][f'is_above_SMA_{i}'] == False) & (ohlcv_data[ticker][f'is_above_SMA_{i}'].shift() == True), 'down', 'no change' ))

    ohlcv_data[ticker][['supertrend_label', 'supertrend']] = supertrend(ohlcv_data[ticker])
    ohlcv_data[ticker]['supertrend_change'] = np.where((ohlcv_data[ticker]['supertrend_label'] == 'upperband') & (ohlcv_data[ticker]['supertrend_label'].shift() == 'lowerband'), 'negative',
                                np.where((ohlcv_data[ticker]['supertrend_label'] == 'lowerband') & (ohlcv_data[ticker]['supertrend_label'].shift() == 'upperband'), 'positive', 'no change'))
```

```{python}
stocks_results = pd.DataFrame()

for i in (stocks):

    aggs = ohlcv_data[i].groupby(pd.Grouper(freq = 'MS')).agg(Close_std = ('Close', 'std'),
                                                                  Close_mean = ('Close', 'mean'),
                                                                  Close_last = ('Close', 'last'),
                                                                  YTD_pct = ('YTD_pct', 'last'),
                                                                  MTD_pct = ('MTD_pct', 'last'),
                                                                  max_drawdown = ('yearly_drawdown_pct', 'max'),
                                                                  max_run_up = ('yearly_run_up_pct', 'max'),
                                                                  mean_volume = ('Volume', 'mean'),
                                                                  above_sma20 = ('is_above_SMA_20', 'last'),
                                                                  above_sma50 = ('is_above_SMA_50', 'last'),
                                                                  above_sma100 = ('is_above_SMA_100', 'last'),
                                                                  above_sma200 = ('is_above_SMA_200', 'last'),
                                                                  supertrend = ('supertrend_label', 'last'),
                                                                  max_200_pct_distance = ('max_200_pct_distance', 'last')

                                                                  )

    aggs['ticker_yf'] = i

    aggs['variability'] = (aggs['Close_std'] / aggs['Close_mean']).round(4) * 100

    aggs['volume_mom_pct_change'] = ((aggs['mean_volume'] / aggs['mean_volume'].shift(1) - 1) * 100).round(3)

    aggs_filtered = aggs#.loc[[2025]]

    stocks_results = pd.concat([stocks_results, aggs_filtered])


# stworzenie końcowej tabeli (dołączam parametry ze słownika)
stocks_results.reset_index(inplace = True)
df = stocks_results.merge(dictionary_stocks, how = 'left', on = 'ticker_yf')

df['index_name'] = np.where(df['in_WIG20'], 'WIG20',
                            np.where(df['in_mWIG40'], 'mWIG40',
                                     np.where(df['in_sWIG80'], 'sWIG80', 'WIG rest')) )

df['market_cap_mln'] = round(df.stocks_number * df.Close_last / 1000000,4)


# dodatkowe kolumny potrzebne w dalszych kalkulacjach
# kosztyki dla stóp zwrotu YTD

bins = [-np.inf,-30,-15,0,20,60,np.inf]

labels = [
    'Bardzo duży spadek (<= 30%)',
    'Duży spadek (-30% - -15%)',
    'Spadek (-15% - 0%)',
    'Neutralnie / lekki wzrost (0% - 20%)',
    'Duży wzrost (20% - 60%)',
    'Ekstremalny wzrost (> 60%)'
]

df['YTD_group'] = pd.cut(
    df['YTD_pct'],
    bins=bins,
    labels=labels,
    right=True,        
    include_lowest=True)

# kosztyki dla stóp zwrotu MTD

bins = [-np.inf,-10,-5,0,5,10,np.inf]

labels = [
    'Duży spadek (<= 10%)',
    'Spadek (-10% - -5%)',
    'Lekki spadek (-5% - 0%)',
    'Lekki wzrost (0% - 5%)',
    'Wzrost (5% - 10%)',
    'Duży wzrost (> 10%)'
]

df['MTD_group'] = pd.cut(
    df['MTD_pct'],
    bins=bins,
    labels=labels,
    right=True,        
    include_lowest=True)

# obsunięcia: Niewielkie (<= 20%); Umiarkowane (20% - 25%); Duże (25% - 40%); Bardzo duże (> 40%)

bins = [-np.inf,20,25,40,np.inf]

labels = [
    'Niewielkie (<= 20%)',
    'Umiarkowane (20% - 25%)',
    'Duże (25% - 40%)',
    'Bardzo duże (> 40%)',]

df['Drawdown_group'] = pd.cut(
    df['max_drawdown'],
    bins=bins,
    labels=labels,
    right=True,        # przedziały domknięte z prawej
    include_lowest=True
)

# volume: Znaczny spadek (< -20%); # Umiarkowany spadek (-20% - 0%) # Umiarkowany wzrost (0% - 20%); Znaczny wzrost (20% - 75%); #Ekstremalny wzrost (> 75%)

bins = [-np.inf,-20,0,20,75,np.inf]

labels = ['Znaczny spadek (<= -20%)','Umiarkowany spadek (-20% - 0%)','Umiarkowany wzrost (0% - 20%)',
    'Znaczny wzrost (20% - 75%)','Ekstremalny wzrost (> 75%)']

df['Volume_change_group'] = pd.cut(
    df['volume_mom_pct_change'],
    bins=bins,
    labels=labels,
    right=True,        # przedziały domknięte z prawej
    include_lowest=True)

# market cap
bins = [-np.inf,30,70,300,1500,10000, np.inf]

labels = ['Bardzo małe (<= 30 mln PLN)', 'Małe (30-70 mln PLN)', 'Średnie (70-300 mln PLN)', 'Duże (300 mln - 1.5 mld PLN)',
          'Bardzo duże (1.5 - 10 mld PLN)', 'Największe (> 10 mld PLN)']

df['Market_cap_group'] = pd.cut(
    df['market_cap_mln'],
    bins=bins,
    labels=labels,
    right=True,        # przedziały domknięte z prawej
    include_lowest=True)

# ATH200 distance
bins = [-np.inf,-75,-50,-25,-15,-5, 0]

labels = ['75-100%', '50-75%', '50-25%', '25-15%','15-5%', '5-0%']

df['ATH200_distance_group'] = pd.cut(
    df['max_200_pct_distance'],
    bins=bins,
    labels=labels,
    right=True,        # przedziały domknięte z prawej
    include_lowest=True)

df_to_analyze = df[df['Date'] == analyzed_month].copy()

df_to_analyze = df[df['Date'] == analyzed_month].copy()


```

```{python}
to_chart = pd.concat([df_to_analyze[['name', 'YTD_pct', 'MTD_pct', 'index_name']].sort_values(by = 'MTD_pct', ascending = False).head(5),
            df_to_analyze[['name', 'YTD_pct', 'MTD_pct', 'index_name']].sort_values(by = 'MTD_pct', ascending = True).head(5)])

to_chart.sort_values(by = 'MTD_pct', ascending = False, inplace= True)            

# mapowanie kolorów na index_name
unique_indexes = to_chart["index_name"].unique()
colors = ['#4A6FA5','#5C677D', '#F2A541'] #plt.cm.Set2(range(len(unique_indexes)))
color_map = dict(zip(unique_indexes, colors))

# przypisanie kolorów
bar_colors = to_chart["index_name"].map(color_map)

fig, ax = plt.subplots(figsize=(8, 5))

ax.barh(
    to_chart["name"],
    to_chart["MTD_pct"],
    color=bar_colors)

# labelki
ax.set_xlabel("Stopa zwrotu (%)")
ax.set_ylabel(None)
ax.set_title("Najwyższe i najniższe stopy zwrotu na GPW - marzec 2026")

# legenda
handles = [
    plt.Line2D([0], [0], color=color_map[idx], lw=6, label=idx)
    for idx in unique_indexes]
ax.legend(handles=handles, title="Indeks", loc = 'lower right')

# wartości na słupkach
for i, v in enumerate(to_chart["MTD_pct"]):
    ax.text(
        v,
        i,
        f"{v:.2f}%",
        va="center",
        ha="left"
    )

#plt.tight_layout()
ax.invert_yaxis() 

plt.axvline(x=0, color="black", linestyle="--", linewidth=1)
plt.axhline(y=4.5,color="red", linestyle = '--', linewidth=1)
plt.show()
```

# Stopy zwrotu i wolumen

::: panel-tabset
## MTD

```{python}
result = (
    df_to_analyze.groupby(['MTD_group', 'index_name']).ticker.value_counts().reset_index(name='count'))

result['percent'] = (round(result['count']/ result.groupby('index_name')['count'].transform('sum')* 100,2))

pivot = result.pivot_table(
    index='MTD_group',
    columns='index_name',
    values=['count', 'percent'],
    aggfunc='sum',
    fill_value=0,
    margins=True,
    margins_name='Razem'
)

order = ['WIG20', 'mWIG40', 'sWIG80', 'WIG rest', 'Razem']

pivot = (
    pivot
        .swaplevel(0, 1, axis=1)
        .sort_index(
            axis=1,
            level=0,
            key=lambda x: pd.Categorical(x, categories=order, ordered=True)))

del pivot[('Razem', 'percent')]

pivot.index.name = 'Stopa zwrotu'
pivot.columns.names = ['Indeks', None]

pivot = pivot.rename(
    columns={'count': 'liczba', 'percent': '%'},
    level=1
)

pivot
```

## YTD

```{python}
result = (
    df_to_analyze.groupby(['YTD_group', 'index_name']).ticker.value_counts().reset_index(name='count'))

result['percent'] = (round(result['count']/ result.groupby('index_name')['count'].transform('sum')* 100,2))

pivot = result.pivot_table(
    index='YTD_group',
    columns='index_name',
    values=['count', 'percent'],
    aggfunc='sum',
    fill_value=0,
    margins=True,
    margins_name='Razem'
)

order = ['WIG20', 'mWIG40', 'sWIG80', 'WIG rest', 'Razem']

pivot = (
    pivot
        .swaplevel(0, 1, axis=1)
        .sort_index(
            axis=1,
            level=0,
            key=lambda x: pd.Categorical(x, categories=order, ordered=True)))

del pivot[('Razem', 'percent')]

pivot.index.name = 'Stopa zwrotu'
pivot.columns.names = ['Indeks', None]

pivot = pivot.rename(
    columns={'count': 'liczba', 'percent': '%'},
    level=1
)

pivot
```

## Wolumeny

```{python}
result = (
    df_to_analyze.groupby(['Volume_change_group', 'index_name']).ticker.value_counts().reset_index(name='count'))

result['percent'] = (round(result['count']/ result.groupby('index_name')['count'].transform('sum')* 100,2))

pivot = result.pivot_table(
    index='Volume_change_group',
    columns='index_name',
    values=['count', 'percent'],
    aggfunc='sum',
    fill_value=0,
    margins=True,
    margins_name='Razem'
)

order = ['WIG20', 'mWIG40', 'sWIG80', 'WIG rest', 'Razem']

pivot = (
    pivot
        .swaplevel(0, 1, axis=1)
        .sort_index(
            axis=1,
            level=0,
            key=lambda x: pd.Categorical(x, categories=order, ordered=True)))

del pivot[('Razem', 'percent')]

pivot.index.name = 'Zmiana % wolumenu M:M'
pivot.columns.names = ['Indeks', None]

pivot = pivot.rename(
    columns={'count': 'liczba', 'percent': '%'},
    level=1)

pivot
```
:::

W minionym miesiącu, jakikolwiek wzrost z pełną świadomością można było określać mianem anomalii. Spośród spółek WIG20 ponad kreską marzec zakończyły tylko 3 spółki, a w przypadku mWIG40 i sWIG80 było to odpowiednio 8 i 12 spółek. Wpłynęło to także na perspektywę YTD i obecnie niezależnie od indeksu, większość spółek balansuje pomiędzy spadkiem a lekkim wzrostem (po 70-85% spółek w każdej z rozpatrywanych grup).

# Najlepsze i najgorsze spółki i sesje

::: panel-tabset
## Wzrosty sesyjne

```{python}
changes = pd.DataFrame(())

for i in stocks:
    x = ohlcv_data[i].loc['2026-03-01':'2026-03-31', ['ticker', 'pct_change', 'Volume_to_Vol_SMA10_pct']].reset_index()
    changes = pd.concat([x, changes])


changes_full_df = changes.merge(dictionary_stocks, how = 'left', left_on = 'ticker', right_on = 'ticker_yf')

changes_full_df['index_name'] = np.where(changes_full_df['in_WIG20'], 'WIG20',
                            np.where(changes_full_df['in_mWIG40'], 'mWIG40',
                                     np.where(changes_full_df['in_sWIG80'], 'sWIG80', 'WIG rest')) )

changes_full_df[['Date', 'name', 'pct_change', 'Volume_to_Vol_SMA10_pct', 'L1_nazwa', 'index_name']].sort_values(by = 'pct_change', ascending = False).head(10).rename(columns={
        'Date': 'Data',
        'name': 'Nazwa',
        'pct_change': 'Zmiana %',
        'Volume_to_Vol_SMA10_pct': 'Wol do Wol SMA10',
        'L1_nazwa': 'Sektor',
        'index_name': 'Indeks'
    }).set_index('Data')

```

## Spadki sesyjne

```{python}
changes = pd.DataFrame(())

for i in stocks:
    x = ohlcv_data[i].loc['2026-03-01':'2026-03-31', ['ticker', 'pct_change', 'Volume_to_Vol_SMA10_pct']].reset_index()
    changes = pd.concat([x, changes])


changes_full_df = changes.merge(dictionary_stocks, how = 'left', left_on = 'ticker', right_on = 'ticker_yf')

changes_full_df['index_name'] = np.where(changes_full_df['in_WIG20'], 'WIG20',
                            np.where(changes_full_df['in_mWIG40'], 'mWIG40',
                                     np.where(changes_full_df['in_sWIG80'], 'sWIG80', 'WIG rest')) )

changes_full_df[['Date', 'name', 'pct_change', 'Volume_to_Vol_SMA10_pct', 'L1_nazwa', 'index_name']].sort_values(by = 'pct_change', ascending = True).head(10).rename(columns={
        'Date': 'Data',
        'name': 'Nazwa',
        'pct_change': 'Zmiana %',
        'Volume_to_Vol_SMA10_pct': 'Wol do Wol SMA10',
        'L1_nazwa': 'Sektor',
        'index_name': 'Indeks'
    }).set_index('Data')
```

## Wzrosty miesięczne

```{python}
df_to_analyze[['Date', 'name', 'MTD_pct', 'volume_mom_pct_change', 'L1_nazwa', 'index_name']].sort_values(by = 'MTD_pct', ascending = False).head(10).rename(columns={
        'Date': 'Data',
        'name': 'Nazwa',
        'MTD_pct': 'Zmiana %',
        'volume_mom_pct_change': 'Średni wolumen M:M',
        'L1_nazwa': 'Sektor',
        'index_name': 'Indeks'
    }).set_index('Data')
```

## Spadki miesięczne

```{python}
df_to_analyze[['Date', 'name', 'MTD_pct', 'volume_mom_pct_change', 'L1_nazwa', 'index_name']].sort_values(by = 'MTD_pct', ascending = True).head(10).rename(columns={
        'Date': 'Data',
        'name': 'Nazwa',
        'MTD_pct': 'Zmiana %',
        'volume_mom_pct_change': 'Średni wolumen M:M',
        'L1_nazwa': 'Sektor',
        'index_name': 'Indeks'
    }).set_index('Data')
```
:::

W kwestii największych spadków i wzrostów zdecydowanie sporo działo się w okół mniejszych spółek. Pierwszą z nich jest Cormay S.A., której notowania 11 i 12 marca rosły kolejno o 35 i 55%, a 27 marca zaliczyły 11-procentową korektę. Spółka podzieliła się [informacją](https://biznes.pap.pl/wiadomosci/firmy/pz-cormay-zakonczyl-przeglad-opcji-strategicznych-dla-projektu-equisse) o zakończeniu przeglądu opcji strategicznych i podpisaniu 5-letniej umowy na produkcję i dystrybucję analizatora biochemicznego, co powinno istotnie wpłynąć na wyniki finansowe spółki. Ostatecznie w marcu spółka wzrosła o 50%.

Gigantyczna zmienność pojawiła się także w przypadku notowań Pure Biologics. Z jednej strony 24,25 i 26 marca pojawiły się 35-40 procentowe wzrosty wynikające z [informacji](https://biznes.pap.pl/wiadomosci/firmy/pure-biologics-sa-112026-wyniki-badania-klinicznego-fazy-0-w-projekcie-pb003g) o pozytywnie zakończonej fazie 0, badaniach klinicznych kandydata na lek; z drugiej zaś 11, 12 i 27 marca spółka zaliczyła 17-20% spadki. Pod koniec miesiąca inwestorzy pozytywnie przyjęli informację o wynikach badań, jednak należy pamiętać że spółka boryka się z dużymi problemami, a jej kurs od początku roku, mimo kilku mocniejszych sesji w marcu, spadł od początku roku o ponad 30 procent.

Wartym wspomnienia są także wydarzenia dotyczące Transpolonii, która w marcu była najmocniej rosnącą spółką na GPW (+112%), czym kontynuowała trend zapoczątkowany w lutym. Pod koniec miesiąca spółka [poinformowała](https://biznes.pap.pl/wiadomosci/firmy/trans-polonia-sa-82026-decyzja-zarzadu-o-udziale-w-procesie-akwizycji-grupy) o udziale w zagranicznej akwizycji podmiotu wielokrotnie większego (kapitalizacja Transpolonia ok. , 320 mln PLN, wartość spółki przejmowanej ok. 2 mld PLN), co docelowo ma prowadzić do skalowania biznesu. 

Wśród sesyjnych spadków jak rzadko znalazł się przedstawiciel WIG20, Dino Polska. Najgorsza w historii sesji spółka jest efektem rozczarowujących wyników finansowych oraz przekazu z konferencji wynikowej. 

# Wskaźniki techniczne

::: panel-tabset
## Średnie kroczące

```{python}
smas_df = pd.DataFrame()
smas = [200, 100, 50, 20]

for i in smas:
    col = f"above_sma{i}"

    above = (
        df_to_analyze
        .groupby('index_name')[col]
        .sum()
        .reset_index(name='above_count')
    )

    total = (
        df_to_analyze
        .groupby('index_name')['ticker']
        .count()
        .reset_index(name='total_count')
    )

    result = above.merge(total, on='index_name')
    result['count'] = round(result['above_count'] / result['total_count'] * 100,2)
    result['dim_name'] = f"powyżej SMA {i}"

    smas_df = pd.concat([smas_df, result[['index_name', 'dim_name', 'count']]])

pivoted = smas_df.pivot_table(
    index='dim_name',
    columns='index_name',
    values='count'
)

row_order = ['powyżej SMA 200','powyżej SMA 100','powyżej SMA 50','powyżej SMA 20']

col_order = ['WIG20','mWIG40','sWIG80','WIG rest']

pt = pivoted.reindex(index=row_order, columns=col_order)

ax = sns.heatmap(pt, fmt=".0f", annot=True, linewidths=0, cmap="YlGn", cbar = False)

plt.title('Procent spółek powyżej średnich kroczących', loc = 'center')
plt.ylabel(None)
plt.xlabel(None)
ax.xaxis.tick_top()
```

## ATH200 dist.

```{python}
st = df_to_analyze.groupby(['index_name','ATH200_distance_group'], as_index = False).ticker.count()

st['value'] = round(st.ticker / st.groupby('index_name').ticker.transform('sum') * 100,2)

st1 = st.pivot_table(index = 'ATH200_distance_group', columns = 'index_name', values = 'value', fill_value=0).reindex(columns=['WIG20','mWIG40','sWIG80','WIG rest'])

st1.index.name = 'Odległość % od ATH200'
st1.columns.names = ['Indeks']

st1
```

## Supertrend

```{python}
st = df_to_analyze.groupby(['index_name','supertrend'], as_index = False).ticker.count()

st['value'] = round(st.ticker / st.groupby('index_name').ticker.transform('sum') * 100,2)

st1 = st.pivot_table(index = 'supertrend', columns = 'index_name', values = 'value').reindex(columns=['WIG20','mWIG40','sWIG80','WIG rest'])

st1.columns.names = ['Indeks']

st1

```

\*wartości jako % spółek w danym indeksie będącym na zakończenie badanego okresa w trendzie wzrostowym (lowerband) lub spadkowym (upperband)
:::

Jeśli chodzi o wskaźniki techniczne, to słabość indeksów na GPW widać już na matrycy średnich kroczących: tu przede wszystkim zauważalna przewaga trendu spadkowego wśród spółek mniejszych - sWIG80 oraz WIG rest. Niezależnie od perspektywy (200, 100, 50 czy 20 sesji), procent spółek powyżej danej średniej nie przekracza nawet 40%. Do ciekawej sytuacji dochodzi natomiast w kwestii spółek WIG20. Aż 70% znajduje się powyżej SMA20, natomiast już tylko 30 i 45 procent przebija średnie 50 i 100 sesyjne. Nietypowo wyglądające proporcje SMA 20 i 50 w przypadku WIG20 to efekt znacznie większych ruchów spadkowych przede wszystkim w okolicach 23 marca, co obniżyło poziom krótkoterminowej średniej. 

O fakcie, że pozytywnie wyglądająca SMA20 w przypadku WIG20 jest tylko pozorem niech świadczy fakt, że wskaźnik supertrend w przypadku każdego z analizowanych indeksów wskazuje ~75% spółek będących w trendzie spadkowym (oznaczone jako upperband, zgodnie z terminologią wskaźnika). 

# Perspektywa sektorowa

::: panel-tabset
## MTD

```{python}
result = (
    df_to_analyze.groupby(['MTD_group', 'L1_nazwa']).ticker.value_counts().reset_index(name='count'))

result['percent'] = (round(result['count']/ result.groupby('L1_nazwa')['count'].transform('sum')* 100,2))

pivot = result.pivot_table(
    index='L1_nazwa',
    columns='MTD_group',
    values=['percent'],
    aggfunc='sum',
    fill_value=0
)


pivot.columns = pivot.columns.droplevel(0)
pivot.index.name = 'Sektor'

plt.figure(figsize=(9, 7))  
ax = sns.heatmap(pivot, fmt=".0f", annot=True, linewidths=0, cmap="YlGn", cbar = False)

plt.title('Rozkład stóp zwrotu według sektora (marzec\'26, %)', loc = 'center')
plt.ylabel(None)
plt.xlabel(None)
ax.xaxis.tick_top()
#ax.set_xticklabels(labels = ['<= -30%', '-30% - -15%', '-15% - 0', '0% - 20%', '20% - 60%', '>60%'], rotation=90, ha='right');
ax.set_xticklabels(labels = ['<= -10%', '-10% - -5%', '-5% - 0', '0% - 5%', '5% - 10%', '>10%'], rotation=90, ha='right');
```

## YTD

```{python}
result = (
    df_to_analyze.groupby(['YTD_group', 'L1_nazwa']).ticker.value_counts().reset_index(name='count'))

result['percent'] = (round(result['count']/ result.groupby('L1_nazwa')['count'].transform('sum')* 100,2))

pivot = result.pivot_table(
    index='L1_nazwa',
    columns='YTD_group',
    values=['percent'],
    aggfunc='sum',
    fill_value=0
)


pivot.columns = pivot.columns.droplevel(0)
pivot.index.name = 'Sektor'

cols = ['Bardzo duży spadek (<= 30%)', 'Duży spadek (-30% - -15%)', 'Spadek (-15% - 0%)', 'Neutralnie / lekki wzrost (0% - 20%)', 'Duży wzrost (20% - 60%)', 'Ekstremalny wzrost (> 60%)']
pivot = pivot.reindex(fill_value=0, columns = cols)

plt.figure(figsize=(9, 7))
ax = sns.heatmap(pivot, fmt=".0f", annot=True, linewidths=0, cmap="YlGn", cbar = False)

plt.title('Rozkład stóp zwrotu według sektora (od początku 2026, %)', loc = 'center')
plt.ylabel(None)
plt.xlabel(None)
ax.xaxis.tick_top()
ax.set_xticklabels(labels = ['<= -30%', '-30% - -15%', '-15% - 0', '0% - 20%', '20% - 60%', '>60%'], rotation=90, ha='right');

```

## Wolumeny

```{python}
result = (
    df_to_analyze.groupby(['Volume_change_group', 'L1_nazwa']).ticker.value_counts().reset_index(name='count'))

result['percent'] = (round(result['count']/ result.groupby('L1_nazwa')['count'].transform('sum')* 100,2))

pivot = result.pivot_table(
    index='L1_nazwa',
    columns='Volume_change_group',
    values=['percent'],
    aggfunc='sum',
    fill_value=0
)


pivot.columns = pivot.columns.droplevel(0)
pivot.index.name = 'Sektor'

plt.figure(figsize=(9, 7))
ax = sns.heatmap(pivot, fmt=".0f", annot=True, linewidths=0, cmap="YlGn", cbar = False)

plt.title('Rozkład zmiany wolumenu M:M (marzec \'26, %)', loc = 'center')
plt.ylabel(None)
plt.xlabel(None)
ax.xaxis.tick_top()
ax.set_xticklabels(labels = ['<= -20%', '-20% - 0%', '0% - 20%', '20% - 75%', '>75%'], rotation=90, ha='right');
```

## SMA

```{python}
smas_df = pd.DataFrame()
smas = [200, 100, 50, 20]

for i in smas:
    col = f"above_sma{i}"

    above = (
        df_to_analyze
        .groupby('L1_nazwa')[col]
        .sum()
        .reset_index(name='above_count')
    )

    total = (
        df_to_analyze
        .groupby('L1_nazwa')['ticker']
        .count()
        .reset_index(name='total_count')
    )

    result = above.merge(total, on='L1_nazwa')
    result['count'] = round(result['above_count'] / result['total_count'] * 100,2)
    result['dim_name'] = f">SMA {i}"

    smas_df = pd.concat([smas_df, result[['L1_nazwa', 'dim_name', 'count']]])

pivoted = smas_df.pivot_table(
    index='L1_nazwa',
    columns='dim_name',
    values='count'
)

col_order = ['>SMA 200','>SMA 100','>SMA 50','>SMA 20']

pt = pivoted.reindex(columns=col_order)

plt.figure(figsize=(9, 7))
ax = sns.heatmap(pt, fmt=".0f", annot=True, linewidths=0, cmap="YlGn", cbar = False)

plt.title('Procent spółek powyżej średnich kroczących według sektora', loc = 'center')
plt.ylabel(None)
plt.xlabel(None)
ax.xaxis.tick_top()
```
:::

Słabość całego rynku oczywiście przekłada się także na perspektywę sektorową, z której nie wyłania się żadna konkretna branża przełamująca negatywne nastroje. Niezależnie od sektora, zdecydowana większość spółek zakończyła miesiąc na minusie. Najlepiej w tym ujęciu wypadł sektor Paliw i energii, z którego 30% zakończyła miesiąc na plusie (a 18% całości na dość sporym, bo conajmniej 10-procentowym). 

W kwestii wolumenu widoczne jest ożywienie względem lutego w przypadku spółek chemiczno-surowcowych, zaś spadki w aktywności inwestorów zauważalne są wolumenie obrotu spółek produkcyjno-przemysłowych oraz technologicznych, gdzie odpowiednio na 37 i 43 spółkach średni dzienny wolumen w porównaniu do lutego był o co najmniej 20% niższy.

# Sygnały techniczne

W ramach nowej sekcji podsumowań miesięcznych, bazując na podstawowych wskaźnikach technicznych - średnich kroczących oraz supertrendzie, przedstawię sygnały wzrostu/spadku, jakie w ostatnim tygodniu marca pojawiły się wśród spółek z indeksu WIG. W przypadku sygnałów bazujących na SMA, weryfikuję czy w którymś z analizowanych dni nastąpiło przecięcie średniej kroczącej 100 lub 200 sesyjnej (w górę lub w dół), natomiast w przypadku supertrendu weryfikuję fakt zmiany obowiązującej linii (z upper na lower lub z lower na upper). 

:::panel-tabset

## Supertrend (positive)

```{python}
# empty DFs 
sma_negative = pd.DataFrame()
sma_positive = pd.DataFrame()

st_negative = pd.DataFrame()
st_positive = pd.DataFrame()

# SMAs signals:

for i in (stocks):
    r1 = ohlcv_data[i][(ohlcv_data[i][['has_crossed_SMA_100', 'has_crossed_SMA_200']].isin(['up','down'])).any(axis =1)].loc['2026-03-25':'2026-03-31'].tail(1)
    r1.reset_index(inplace = True)
    if r1[['has_crossed_SMA_100', 'has_crossed_SMA_200']].isin(['up']).any(axis=1).any(): sma_positive = pd.concat([sma_positive, r1])
    if r1[['has_crossed_SMA_100', 'has_crossed_SMA_200']].isin(['down']).any(axis=1).any(): sma_negative = pd.concat([sma_negative, r1])

# supertrend:
for i in stocks:
    st = ohlcv_data[i][
        (ohlcv_data[i]['supertrend_change'].isin(['positive','negative']))
    ].loc['2026-03-25':'2026-03-31'].tail(1)

    st.reset_index(inplace=True)

    if not st.empty:
        if st['supertrend_change'].iloc[0] == 'positive':
            st_positive = pd.concat([st_positive, st])
        elif st['supertrend_change'].iloc[0] == 'negative':
            st_negative = pd.concat([st_negative, st])

st_positive[['ticker', 'Date', 'pct_change', 'YTD_pct', 'MTD_pct', 'is_above_SMA_100', 'has_crossed_SMA_100', 'is_above_SMA_200', 'has_crossed_SMA_200']].set_index('ticker')
```

## Supertrend (negative)
```{python}
st_negative[['ticker', 'Date', 'pct_change', 'YTD_pct', 'MTD_pct', 'is_above_SMA_100', 'has_crossed_SMA_100', 'is_above_SMA_200', 'has_crossed_SMA_200']].set_index('ticker')
```

## SMA (positive)
```{python}
sma_positive[['ticker', 'Date', 'pct_change', 'YTD_pct', 'MTD_pct', 'is_above_SMA_100', 'has_crossed_SMA_100', 'is_above_SMA_200', 'has_crossed_SMA_200']].set_index('ticker')
```

## SMA (negative)
```{python}
sma_negative[['ticker', 'Date', 'pct_change', 'YTD_pct', 'MTD_pct', 'is_above_SMA_100', 'has_crossed_SMA_100', 'is_above_SMA_200', 'has_crossed_SMA_200']].set_index('ticker')
```
:::

# Na zakończenie

Miniony miesiąc dla zdecydowanej większości spółek upłynął pod znakiem spadków, choć spośród kilkuset spółek możliwym było wyselekcjonowanie tych, które inwestorom zapewniły całkiem solidny wzrost za pomocą wydarzeń fundamentalnych takich jak postępy w komercjalizacji produktów czy skalowanie biznesu. Niemniej, dopóki sytuacja na Bliskim Wschodzie nie zostanie wyjaśniona, ceny na giełdach będą pod presją niedźwiedzi. 