---
title: "Podsumowanie 2025 roku na GPW"
subtitle: "Duże wzrosty, lecz nie dla każdego"
author: "Tomasz Szczerbicki"
date: 2026-01-22
categories: [Analiza techniczna, GPW, WIG, WIG20, mWIG40, sWIG80, podsumowanie roczne]
execute:
  echo: false
  warning: false
  message: false
  freeze: false
toc: True
---

Za nami rok 2025, który na Giełdzie Papierów Wartościowych obfitował w imponujące wzrosty. W tym wpisie podsumuję kto skorzystał, a kto stracił najbardziej; jak duże ryzyka pojawiły się w trakcie roku i jak wygląda krajobraz na polskiej giełdzie po tak intensywnym okresie. Przegląd ten zostanie przeprowadzony w podziale na cztery części: WIG20, mWIG40, sWIG80 oraz WIG pozostałe.

```{python}
import pandas as pd
import numpy as np
import yfinance as yf
import talib
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('/Users/tomasz/Desktop/quarto2/styles/blog_style.mplstyle')

# funkcje
def wtd(df: pd.DataFrame):
    d1 = df.copy()
    weekly_close = d1['Close'].resample('W-FRI').last().shift()
    d1['weekly_close'] = weekly_close.reindex(d1.index, method = 'bfill')
    d1['WTD_%'] = (d1['Close'] / d1['weekly_close'] - 1) * 100
    return d1['WTD_%'].astype(float).round(4)

def mtd(df: pd.DataFrame):
    d1 = df.copy()
    month_map = dict(d1['Close'].groupby([d1.index.year, d1.index.month]).last())
    d1['prev_month_close'] = [month_map.get((d.year if d.month > 1 else d.year - 1,12 if d.month == 1 else d.month - 1), np.nan) for d in d1.index]
    d1['MTD_%'] = (d1['Close'] / d1['prev_month_close'] - 1) * 100
    return d1['MTD_%'].astype(float).round(4)

def ytd(df: pd.DataFrame):
    d1 = df.copy()
    year_map = dict(d1['Close'].groupby([d1.index.year]).last())
    d1['prev_year_close'] = [year_map.get(d.year -1 , np.nan) for d in d1.index]
    d1['YTD_%'] = (d1['Close'] / d1['prev_year_close'] - 1) * 100
    return d1['YTD_%'].astype(float).round(4)

def ATR(df: pd.DataFrame, n = 14):
    d1 = df.copy()
    d1['H-L'] = d1['High'] - d1['Low']
    d1['H-PC'] = d1['High'] - d1['Close'].shift(1)
    d1['L-PC'] = d1['Low'] - d1['Close'].shift(1)
    d1['TR'] = d1[['H-L', 'H-PC', 'L-PC']].max(axis = 1)
    d1['ATR'] = d1['TR'].ewm(span = n, min_periods = n).mean()
    return d1['ATR']

def supertrend(df: pd.DataFrame, atr_multiplier=3, atr_length = 15):
    d1 = df.copy()
    current_average_high_low = (d1['High']+d1['Low'])/2
    d1['atr'] = talib.ATR(d1['High'], d1['Low'], d1['Close'], timeperiod= atr_length)
    d1.dropna(inplace=True)

    d1['basicUpperband'] = current_average_high_low + (atr_multiplier * d1['atr'])
    d1['basicLowerband'] = current_average_high_low - (atr_multiplier * d1['atr'])
    first_upperBand_value = d1['basicUpperband'].iloc[0]
    first_lowerBand_value = d1['basicLowerband'].iloc[0]
    upperBand = [first_upperBand_value]
    lowerBand = [first_lowerBand_value]

    for i in range(1, len(d1)):
        if d1['basicUpperband'].iloc[i] < upperBand[i-1] or d1['Close'].iloc[i-1] > upperBand[i-1]:
            upperBand.append(d1['basicUpperband'].iloc[i])
        else:
            upperBand.append(upperBand[i-1])

        if d1['basicLowerband'].iloc[i] > lowerBand[i-1] or d1['Close'].iloc[i-1] < lowerBand[i-1]:
            lowerBand.append(d1['basicLowerband'].iloc[i])
        else:
            lowerBand.append(lowerBand[i-1])

    d1['upperband'] = upperBand
    d1['lowerband'] = lowerBand

    d1['has_crossed_upper'] = np.where((d1['Close'].shift(1) < d1['upperband'].shift(1)) & (d1['Close'] >= d1['upperband']), 1,0)
    d1['has_crossed_lower'] = np.where((d1['Close'].shift(1) > d1['lowerband'].shift(1)) & (d1['Close'] <= d1['lowerband']), 1,0)
    
    supertrend = ['upperband']
    for i in range(1, len(d1)):
        if d1['has_crossed_upper'].iloc[i] == 1:
            supertrend.append('lowerband')
        elif d1['has_crossed_lower'].iloc[i] == 1:
            supertrend.append('upperband')
        else:
            supertrend.append(supertrend[i-1])  # poprzednia wartość

    d1['supertrend_label'] = supertrend
    d1['supertrend'] = np.where(d1['supertrend_label'] == 'upperband', d1['upperband'], d1['lowerband'])
    d1.drop(['basicUpperband', 'basicLowerband'], axis=1, inplace=True)
    return d1[['supertrend_label', 'supertrend']]

def drawdown(df: pd.DataFrame):
    d1 = df.copy()
    d1['return'] = d1['Close'].pct_change()
    d1['cum_return'] = (1+ d1['return']).groupby(d1.index.year).cumprod()
    d1['cum_roll_max'] = d1['cum_return'].groupby(d1.index.year).cummax()
    d1['drawdown'] = d1['cum_roll_max'] - d1['cum_return']
    d1['drawdown_pct'] = d1['drawdown'] / d1['cum_roll_max'] * 100
    return d1['drawdown_pct'].astype(float).round(4)

def run_up(df: pd.DataFrame):
    d1 = df.copy()
    d1['return'] = d1['Close'].pct_change()
    d1['cum_return'] = (1+ d1['return']).groupby(d1.index.year).cumprod()
    d1['cum_roll_min'] = d1['cum_return'].groupby(d1.index.year).cummin()
    d1['run_up'] = d1['cum_return'] - d1['cum_roll_min']
    d1['run_up_pct'] = d1['run_up'] / d1['cum_roll_min'] * 100
    return d1['run_up_pct'].astype(float).round(4)

# wgranie słownika

dictionary_stocks = pd.read_excel('/Users/tomasz/Desktop/quarto2/shared_files/spolki.xlsx', index_col = 0)
```

```{python}
# starter code
stocks = dictionary_stocks[dictionary_stocks['in_WIG'] == True].ticker_yf.to_list()
ohlcv_data = {}

for ticker in stocks:
    temp = yf.download(ticker, start = '2024-01-01', interval = '1d')
    temp.dropna(how = 'any', inplace = True)

    ohlcv_data[ticker] = temp
    ohlcv_data[ticker].columns = ['Close', 'High', 'Low', 'Open', 'Volume']
    ohlcv_data[ticker]['ticker'] = ticker

    #yahoo finance ma błąd w danych dla MOL za okres 30.12.2024 - 10.06.2025. W to miejsce wstawiam dane stooq
    if ticker == 'MOL.WA':
        l1 = pd.read_csv('/Users/tomasz/Desktop/quarto2/shared_files/t1.csv')['Close'].to_list()
        ohlcv_data['MOL.WA'].loc[ '2024-12-30':'2025-06-10', 'Close'] = l1
    
    # podobnie błąd dla Dadelo w jednym dniu
    if ticker == 'DAD.WA':
        ohlcv_data['DAD.WA'].loc['2025-04-25', 'Close'] = 28.30

    ohlcv_data[ticker]['pct_change'] = round(ohlcv_data[ticker]['Close'].pct_change() * 100,4)
    ohlcv_data[ticker]['WTD_pct'] = wtd(ohlcv_data[ticker])
    ohlcv_data[ticker]['MTD_pct'] = mtd(ohlcv_data[ticker])
    ohlcv_data[ticker]['YTD_pct'] = ytd(ohlcv_data[ticker])

    ohlcv_data[ticker]['yearly_drawdown_pct'] = drawdown(ohlcv_data[ticker])
    ohlcv_data[ticker]['yearly_run_up_pct'] = run_up(ohlcv_data[ticker])

    for i in [50,100,200,300]:
        l1 = ohlcv_data[ticker]['Close'].rolling(i).max()
        ohlcv_data[ticker][f'is_{i}_max'] = ohlcv_data[ticker]['Close'] == l1
        ohlcv_data[ticker][f'max_{i}_pct_distance'] = (ohlcv_data[ticker]['Close'] /  l1 - 1) * 100

    for i in [10, 20, 50,100,200]:
        ohlcv_data[ticker][f'SMA_{i}'] = ohlcv_data[ticker]['Close'].rolling(i).mean()
        ohlcv_data[ticker][f'is_above_SMA_{i}'] = ohlcv_data[ticker]['Close'] > ohlcv_data[ticker][f'SMA_{i}']
        ohlcv_data[ticker][f'has_crossed_SMA_{i}'] = np.where((ohlcv_data[ticker][f'is_above_SMA_{i}'] == True) & (ohlcv_data[ticker][f'is_above_SMA_{i}'].shift() == False), 'up',
                                                            np.where((ohlcv_data[ticker][f'is_above_SMA_{i}'] == False) & (ohlcv_data[ticker][f'is_above_SMA_{i}'].shift() == True), 'down', 'no change' ))

    ohlcv_data[ticker][['supertrend_label', 'supertrend']] = supertrend(ohlcv_data[ticker])
    ohlcv_data[ticker]['supertrend_change'] = np.where((ohlcv_data[ticker]['supertrend'] == 'upperband') & (ohlcv_data[ticker]['supertrend'].shift() == 'lowerband'), 'negative',
                                np.where((ohlcv_data[ticker]['supertrend'] == 'lowerband') & (ohlcv_data[ticker]['supertrend'].shift() == 'upperband'), 'positive', 'no change'))
```

```{python}
stocks_results = pd.DataFrame()

for i in (stocks):

    aggs = ohlcv_data[i].groupby(ohlcv_data[i].index.year).agg(Close_std = ('Close', 'std'),
                                                                  Close_mean = ('Close', 'mean'),
                                                                  Close_last = ('Close', 'last'),
                                                                  YTD_pct = ('YTD_pct', 'last'),
                                                                  max_drawdown = ('yearly_drawdown_pct', 'max'),
                                                                  max_run_up = ('yearly_run_up_pct', 'max'),
                                                                  mean_volume = ('Volume', 'mean')
                                                                  )

    aggs['ticker_yf'] = i

    aggs['variability'] = (aggs['Close_std'] / aggs['Close_mean']).round(4) * 100

    aggs['volume_yoy_pct_change'] = ((aggs['mean_volume'] / aggs['mean_volume'].shift(1) - 1) * 100).round(3)

    aggs_filtered = aggs.loc[[2025]]

    stocks_results = pd.concat([stocks_results, aggs_filtered])


# stworzenie końcowej tabeli (dołączam parametry ze słownika)
df = stocks_results.merge(dictionary_stocks, how = 'left', on = 'ticker_yf')

df['index_name'] = np.where(df['in_WIG20'], 'WIG20',
                            np.where(df['in_mWIG40'], 'mWIG40',
                                     np.where(df['in_sWIG80'], 'sWIG80', 'WIG rest')) )

df['market_cap_mln'] = round(df.stocks_number * df.Close_last / 1000000,4)


# dodatkowe kolumny potrzebne w dalszych kalkulacjach
# kosztyki dla stóp zwrotu 

bins = [-np.inf,-30,-15,0,20,60,np.inf]

labels = [
    'Bardzo duży spadek (<= 30%)',
    'Duży spadek (-30% - -15%)',
    'Spadek (-15% - 0%)',
    'Neutralnie / lekki wzrost (0% - 20%)',
    'Duży wzrost (20% - 60%)',
    'Ekstremalny wzrost (> 60%)'
]

df['YTD_group'] = pd.cut(
    df['YTD_pct'],
    bins=bins,
    labels=labels,
    right=True,        
    include_lowest=True)

# obsunięcia: Niewielkie (<= 20%); Umiarkowane (20% - 25%); Duże (25% - 40%); Bardzo duże (> 40%)

bins = [-np.inf,20,25,40,np.inf]

labels = [
    'Niewielkie (<= 20%)',
    'Umiarkowane (20% - 25%)',
    'Duże (25% - 40%)',
    'Bardzo duże (> 40%)',]

df['Drawdown_group'] = pd.cut(
    df['max_drawdown'],
    bins=bins,
    labels=labels,
    right=True,        # przedziały domknięte z prawej
    include_lowest=True
)

# volume: Znaczny spadek (< -20%); # Umiarkowany spadek (-20% - 0%) # Umiarkowany wzrost (0% - 20%); Znaczny wzrost (20% - 75%); #Ekstremalny wzrost (> 75%)

bins = [-np.inf,-20,0,20,75,np.inf]

labels = ['Znaczny spadek (<= -20%)','Umiarkowany spadek (-20% - 0%)','Umiarkowany wzrost (0% - 20%)',
    'Znaczny wzrost (20% - 75%)','Ekstremalny wzrost (> 75%)']

df['Volume_change_group'] = pd.cut(
    df['volume_yoy_pct_change'],
    bins=bins,
    labels=labels,
    right=True,        # przedziały domknięte z prawej
    include_lowest=True)

# market cap
bins = [-np.inf,30,70,300,1500,10000, np.inf]

labels = ['Bardzo małe (<= 30 mln PLN)', 'Małe (30-70 mln PLN)', 'Średnie (70-300 mln PLN)', 'Duże (300 mln - 1.5 mld PLN)',
          'Bardzo duże (1.5 - 10 mld PLN)', 'Największe (> 10 mld PLN)']

df['Market_cap_group'] = pd.cut(
    df['market_cap_mln'],
    bins=bins,
    labels=labels,
    right=True,        # przedziały domknięte z prawej
    include_lowest=True)
```

```{python}
d_1 = df[df['in_WIG20'] == True]['YTD_pct']
d_2 = df[df['in_mWIG40'] == True]['YTD_pct'].dropna()
d_3 = df[df['in_sWIG80'] == True]['YTD_pct'].dropna()
d_4 = df[(df['in_WIG'] == True) & (df['in_WIG140'] == False) ]['YTD_pct'].dropna()
d = [ d_1, d_2, d_3, d_4]

fig = plt.figure(figsize =(10, 5))
ax = fig.add_axes([0, 0, 1, 1])
ax.set_ylabel('Stopa zwrotu za 2025 rok (%)')
bp = ax.boxplot(d, labels=['WIG20', 'mWIG40', 'sWIG80', 'WIG pozostałe'], patch_artist=True)
plt.title("Stopy zwrotu na GPW w podziale na indeksy")
ax.axhline(0, linestyle='--', linewidth=1, color = 'red')

colors = plt.rcParams['axes.prop_cycle'].by_key()['color']
for patch, color in zip(bp['boxes'], colors):
    patch.set_facecolor(color)
    patch.set_alpha(0.7)


# === DODANIE WARTOŚCI MEDIANY NA WYKRES ===
for i, median in enumerate(bp['medians'], start=1):
    y = median.get_ydata()[0]  # wartość mediany
    ax.text(
        i, y,
        f'ME: {y:.2f}%',
        ha='center',
        va='bottom',
        fontsize=9,
        fontweight='bold'
    )

plt.show()
```

Spoglądajac na rozkład stóp zwrotu względem indeksu widać, że mediana stóp zwrotu w każdym przypadku znajduje się powyżej zera. Niemniej, niekwestionowanymi zwycięzcami zostają blue-chips - mediana stóp zwrotu dla indeksu WIG20 wyniosła 42.70% i tylko jedna spółka (CCC) zakończyła rok na czerwono. Na im mniejsze spółki spoglądamy, tym mniejsza jest mediana i mniejsza koncentracja wyników wokół niej. Co warte podkreślenia, rezultaty osiągnięte przez mWIG40 i sWIG80 (mediany kolejno 21.24% i 14.54%) również należy postrzegać pozytywnie.

# WIG20

::: panel-tabset
## Stopy zwrotu

```{python}
g = df.loc[df['in_WIG20']].groupby('YTD_group')['ticker']

summary = g.count().to_frame('Liczba')
summary['Udział w całości (%)'] = round(g.count() / g.count().sum() * 100,2)

summary.index.name = 'Stopy zwrotu (%)'

summary
```

## Top 5

```{python}
top = df.loc[df['in_WIG20']][['name', 'L1_nazwa', 'YTD_pct', 'max_drawdown', 'volume_yoy_pct_change']].sort_values(by = 'YTD_pct', ascending= False).head(5)

top.columns = ['Nazwa', 'Sektor', 'Stopa zwrotu 2025', 'Maks obsuniecie', 'Zmiana wolumenu R:R']

top.set_index(['Nazwa','Sektor'], inplace= True)

top
```

## Flop 5

```{python}
flop = df.loc[df['in_WIG20']][['name', 'L1_nazwa', 'YTD_pct', 'max_drawdown', 'volume_yoy_pct_change']].sort_values(by = 'YTD_pct', ascending= True).head(5)

flop.columns = ['Nazwa', 'Sektor', 'Stopa zwrotu 2025', 'Maks obsuniecie', 'Zmiana wolumenu R:R']

flop.set_index(['Nazwa','Sektor'], inplace= True)

flop
```

## Wolumeny

```{python}
volumes = df.loc[df['in_WIG20']].groupby(['YTD_group','Volume_change_group'], as_index= False)['ticker'].count().pivot_table(index = 'YTD_group', columns = 'Volume_change_group', values = 'ticker', aggfunc="sum", fill_value = 0, margins = True, margins_name = 'Razem')

volumes.index.name = 'Stopy zwrotu (%)'
volumes.columns.name = 'Zmiana śr. wolumenu R:R (%)'

volumes
```

## Maks Obsunięcie

```{python}
ytd_groups = df.loc[df['in_WIG20']].groupby(['YTD_group','Drawdown_group'], as_index= False)['ticker'].count().pivot_table(index = 'YTD_group', columns = 'Drawdown_group', values = 'ticker', aggfunc="sum",fill_value = 0, margins = True, margins_name = 'Razem')

ytd_groups.index.name = 'Stopy zwrotu (%)'
ytd_groups.columns.name = 'Maksymalne obsunięcie kursu (%)'

ytd_groups
```

## Kapitalizacje

```{python}
g = df.loc[df['in_WIG20']].groupby('Market_cap_group')['ticker']

summary = g.count().to_frame('Liczba')
summary['Udział w całości (%)'] = round(g.count() / g.count().sum() * 100,2)

summary.index.name = 'Kapitalizacja na koniec 2025r'

summary
```
:::

Jeżeli mowa o indeksie WIG20, w minionym roku trzeba było mieć spore szczęście aby źle trafić. Z 20 spółek tylko **CCC** zakończyło rok pod kreską i to dość poważnie, bo na poziomie -35%, choć to i tak nie jest najmniejszy wymiar kary, bo w najgorszym wypadku obsunęło się aż o 53%. Pozostałe cztery spółki w zakładce "Flop 5" wygenerowały już dodatnią stopę zwrotu, a za dobrą kondycję indeksu niech świadczy fakt, że piąta najsłabsza spółka urosła o prawie 25%. W tym miejscu warto także zwrócić uwagę na **Zabka**. Choć stopa wzrostu zadowalająca, bo niemal 19%, to w oczy rzuca się niższy o 42% średni dzienny wolumen, co stanowi schłodzenie po debiutanckim roku 2024.

Aż szesnaście spółek wygenerowało wzrost powyżej 20%, a królowały przede wszystkim dwa państwowe giganty: **KGHM** i **PKN Orlen** ze wzrostami kolejno 144 i 119%. W przypadku potentata z branży paliwowej trend wzrostowy można uznac za wzorowy, ponieważ w trakcie roku kurs najmnocniej obsunął się o niespełna 12%.

Wyższym stopom zwrotu w minionym roku towarzyszył zwiększony wolumen w przypadku 13 spółek indeksu WIG20, jednakże tylko w przypadku dwóch ten wzrost przekroczył 75%. W kontekście zarządzania ryzykiem wyzwania były zdecydowanie ograniczone - tylko jedna spółka zaliczyła obsunięcie kursu o 40% lub więcej. Najczęściej mieliśmy do czynienia z niewielkim, maksymalnie 20% (9 przypadków) lub umiarkownaym, mieszczącym sie w granicach 25% (8 przypadków).

W kwestii struktury wielkościowej spółek indeksu WIG20, rok 2025 kończymy w składzie 3 spółek o kapitalizacji pomiedzy 1.5 a 10 miliarda złotych oraz 17 spółek wycenianych przez rynek na ponad 10 miliardów złotych.

# mWIG40

::: panel-tabset
## Stopy zwrotu

```{python}
g = df.loc[df['in_mWIG40']].groupby('YTD_group')['ticker']

summary = g.count().to_frame('Liczba')
summary['Udział w całości (%)'] = round(g.count() / g.count().sum() * 100,2)

summary.index.name = 'Stopy zwrotu (%)'

summary
```

## Top 5

```{python}
top = df.loc[df['in_mWIG40']][['name', 'L1_nazwa', 'YTD_pct', 'max_drawdown', 'volume_yoy_pct_change']].sort_values(by = 'YTD_pct', ascending= False).head(5)

top.columns = ['Nazwa', 'Sektor', 'Stopa zwrotu 2025', 'Maks obsuniecie', 'Zmiana wolumenu R:R']

top.set_index(['Nazwa','Sektor'], inplace= True)

top
```

## Flop 5

```{python}
flop = df.loc[df['in_mWIG40']][['name', 'L1_nazwa', 'YTD_pct', 'max_drawdown', 'volume_yoy_pct_change']].sort_values(by = 'YTD_pct', ascending= True).head(5)

flop.columns = ['Nazwa', 'Sektor', 'Stopa zwrotu 2025', 'Maks obsuniecie', 'Zmiana wolumenu R:R']

flop.set_index(['Nazwa','Sektor'], inplace= True)

flop
```

## Wolumeny

```{python}
volumes = df.loc[df['in_mWIG40']].groupby(['YTD_group','Volume_change_group'], as_index= False)['ticker'].count().pivot_table(index = 'YTD_group', columns = 'Volume_change_group', values = 'ticker', aggfunc="sum",fill_value = 0,margins = True, margins_name = 'Razem')

volumes.index.name = 'Stopy zwrotu (%)'
volumes.columns.name = 'Zmiana śr. wolumenu R:R (%)'

volumes
```

## Maks Obsunięcie

```{python}
ytd_groups = df.loc[df['in_mWIG40']].groupby(['YTD_group','Drawdown_group'], as_index= False)['ticker'].count().pivot_table(index = 'YTD_group', columns = 'Drawdown_group', values = 'ticker', aggfunc="sum",fill_value = 0,margins = True, margins_name = 'Razem')

ytd_groups.index.name = 'Stopy zwrotu (%)'
ytd_groups.columns.name = 'Maksymalne obsunięcie kursu (%)'

ytd_groups
```

## Kapitalizacje

```{python}
g = df.loc[df['in_mWIG40']].groupby('Market_cap_group')['ticker']

summary = g.count().to_frame('Liczba')
summary['Udział w całości (%)'] = round(g.count() / g.count().sum() * 100,2)

summary.index.name = 'Kapitalizacja na koniec 2025r'

summary
```
:::

Zerkając na notowania tzw. mid-capów zauważamy więcej czerwieni, niż miało to miejsce przy WIG20. Spadek kursu odnotowało 11 z 40 spółek. Najsłabiej z indeksu poradził sobie Text (spadek o 34%). Istotnie (o 20-28%) przecenione zostały także spółki takie jak Amrest, Polenergia i Wirtualna Polska. Co natomiast różni te podmioty od TEXT-u, to zdecydowany, 130-150 procentowy wzrost średniego dziennego wolumenu na każdym z tych walorów.  

W kategorii wzrostów, o ponad 100% wzrosły trzy podmioty: Asseco Poland, Tauron i NEWAG. W top5 znalazły się także Millenium (kolejny z banków, po Mbank i Pekao z WIG20) oraz Lubawa. Tutaj wzrosty to kolejno 83 i 87%. Jeżeli jednak mowa o ostatniej z wymienionych spółek, część inwestorów, która dołączyła w trakcie roku z pewnością będzie rozczarowana, bowiem maksymalnie obsunięcie kursu wyniosło aż 40%. 

Podobne, lub większe obsunięcie kursu wystąpiło łącznie w przypadku 6 spółek analizowanego indeksu. Najcześciej, bo aż 18 razy odnotowywane były maksymalne przeceny mieszczące się w granicach 20%, więc proporcja spółek w tej grupie została zachowana względem rezultatu WIG20. 

Pomimo tego, że spółki indeksu mWIG40 poradziły sobie gorzej niż spółki WIG20, to w ponad 70% przypadków widoczny jest wzrost średniego dziennego wolumenu (dla porównania WIG20 to 65%). Możliwe zatem, że inwestorzy po zrealizowaniu zadowalających zysków na blue-chipach kolejnych szans zaczęli szukać na walorach mid-cap. 

Jeżeli chodzi o kapitalizacje spółek na koniec 2025 roku, zauważalna jest duży rozstrzał - z jednej strony 8 spółek o kapitalizacji w przedziale 300 mln - 1,5 mld zł, z drugiej zaś 8 spółek o kapitalizacji przekraczającej 10 mld zł. Najczęściej jednak w przypadku tego indeksu mamy do czynienia ze spółkami bardzo dużymi, o kapitalizacji w granicach 1,5 - 10 mld złotych. 


*\*w analizie spółek indeksu mWIG40 została pominięta spółka Arlen, która zaczęła być notowana na giełdzie w czerwcu 2025 roku.*

# sWIG80

::: panel-tabset
## Stopy zwrotu

```{python}
g = df.loc[df['in_sWIG80']].groupby('YTD_group')['ticker']

summary = g.count().to_frame('Liczba')
summary['Udział w całości (%)'] = round(g.count() / g.count().sum() * 100,2)

summary.index.name = 'Stopy zwrotu (%)'

summary
```

## Top 5

```{python}
top = df.loc[df['in_sWIG80']][['name', 'L1_nazwa', 'YTD_pct', 'max_drawdown', 'volume_yoy_pct_change']].sort_values(by = 'YTD_pct', ascending= False).head(5)

top.columns = ['Nazwa', 'Sektor', 'Stopa zwrotu 2025', 'Maks obsuniecie', 'Zmiana wolumenu R:R']

top.set_index(['Nazwa','Sektor'], inplace= True)

top
```

## Flop 5

```{python}
flop = df.loc[df['in_sWIG80']][['name', 'L1_nazwa', 'YTD_pct', 'max_drawdown', 'volume_yoy_pct_change']].sort_values(by = 'YTD_pct', ascending= True).head(5)

flop.columns = ['Nazwa', 'Sektor', 'Stopa zwrotu 2025', 'Maks obsuniecie', 'Zmiana wolumenu R:R']

flop.set_index(['Nazwa','Sektor'], inplace= True)

flop
```

## Wolumeny

```{python}
volumes = df.loc[df['in_sWIG80']].groupby(['YTD_group','Volume_change_group'], as_index= False)['ticker'].count().pivot_table(index = 'YTD_group', columns = 'Volume_change_group', values = 'ticker', aggfunc="sum",fill_value = 0, margins = True, margins_name = 'Razem')

volumes.index.name = 'Stopy zwrotu (%)'
volumes.columns.name = 'Zmiana śr. wolumenu R:R (%)'

volumes
```

## Maks Obsunięcie

```{python}
ytd_groups = df.loc[df['in_sWIG80']].groupby(['YTD_group','Drawdown_group'], as_index= False)['ticker'].count().pivot_table(index = 'YTD_group', columns = 'Drawdown_group', values = 'ticker', aggfunc="sum",fill_value = 0,margins = True, margins_name = 'Razem')

ytd_groups.index.name = 'Stopy zwrotu (%)'
ytd_groups.columns.name = 'Maksymalne obsunięcie kursu (%)'

ytd_groups
```

## Kapitalizacje

```{python}
g = df.loc[df['in_sWIG80']].groupby('Market_cap_group')['ticker']

summary = g.count().to_frame('Liczba')
summary['Udział w całości (%)'] = round(g.count() / g.count().sum() * 100,2)

summary.index.name = 'Kapitalizacja na koniec 2025r'

summary
```
:::

Przechodząc do indeksu sWIG80 widoczny jest ponowny spadek przeciętnych wyników względem WIG20 i mWIG40. Zwiększa się natomiast rozstrzał osiągniętych rezultatów - przy odpowiedniej selekcji możliwe było osiągnięcie nieporównywalnie lepszych wyników. Choć ekstremalny wzrost powyżej 60% zaliczyło już "tylko" 20% spółek, to wciąż aż 60% kończyło rok nad kreską. Najbardziej imponujące wzrosty odnotował Polimex (292%), a w dalszej kolejności Dadelo (177%) i Bumech (171%). Po drugiej stronie, wśród największy outsiderów znajdują się Arctic (-48%), Pekabex (-35%) i Ryvu (-30%). 

W przypadku Ryvu w oczy bardzo mocno rzuca się 750-procentowy wzrost średniego dziennego wolumenu w porównaniu do roku 2024. W zasadzie przez cały rok zauważalna była zwiększona aktywność inwestorów, zaś apogeum przypada na końcówke lutego i negatywne informacje związane z restrukturyzacją przedsiębiorstwa. 

Analizując średnie dzienne wolumeny widocznym jest, że dynamika zmian nie jest na poziomie WIG20 czy mWIG40. Jakikolwiek wzrost w tej kategorii zanotowało 48% spółek, choć co istotne aż 19 dotyczy ekstremalny wzrost wolumenu. Co do zasady, im większa stopa zwrotu z danego waloru, tym większy wzrost wolumenu. Interesująco wygląda sytuacja po drugiej stronie, ponieważ na 19 spółek, których kurs osłabił się o 15-30 procent, w aż 6 średni wolumen dzienny spadł o ponad 20%. Możemy zatem przypuszczać, że brak dodatkowej podaży przy istotnych osunięciach kursu jest potwierdzeniem wiary w te walory w długim terminie. 

Jeśli natomiast mowa o kapitalizacjach, sWIG80 zakończył rok posiadając w swoim portfelu przede wszystkim spółki wyceniane na 300 mln - 1.5 mld złotych (71.25% całego indeksu). Drugą w kolejności grupą są spółki bardzo duże o kapitalizacji od 1.5 do 10 mld, a najmniejsza grupę stanowią spółki z drugiej strony rozkładu - te o kapitalizacji 70-300 mln złotych. 

*\*w analizie spółek indeksu sWIG80 została pominięta spółka Diagnostyka, która zaczęła być notowana na giełdzie w lutym 2025 roku.*

# WIG rest

::: panel-tabset
## Stopy zwrotu

```{python}
g = df.loc[(df['in_WIG'] == True) & (df['in_WIG140'] == False)].groupby('YTD_group')['ticker']

summary = g.count().to_frame('Liczba')
summary['Udział w całości (%)'] = round(g.count() / g.count().sum() * 100,2)

summary.index.name = 'Stopy zwrotu (%)'

summary
```

## Top 5

```{python}
top = df.loc[(df['in_WIG'] == True) & (df['in_WIG140'] == False)][['name', 'L1_nazwa', 'YTD_pct', 'max_drawdown', 'volume_yoy_pct_change']].sort_values(by = 'YTD_pct', ascending= False).head(5)

top.columns = ['Nazwa', 'Sektor', 'Stopa zwrotu 2025', 'Maks obsuniecie', 'Zmiana wolumenu R:R']

top.set_index(['Nazwa','Sektor'], inplace= True)

top
```

## Flop 5

```{python}
flop = df.loc[(df['in_WIG'] == True) & (df['in_WIG140'] == False)][['name', 'L1_nazwa', 'YTD_pct', 'max_drawdown', 'volume_yoy_pct_change']].sort_values(by = 'YTD_pct', ascending= True).head(5)

flop.columns = ['Nazwa', 'Sektor', 'Stopa zwrotu 2025', 'Maks obsuniecie', 'Zmiana wolumenu R:R']

flop.set_index(['Nazwa','Sektor'], inplace= True)

flop
```

## Wolumeny

```{python}
volumes = df.loc[(df['in_WIG'] == True) & (df['in_WIG140'] == False)].groupby(['YTD_group','Volume_change_group'], as_index= False)['ticker'].count().pivot_table(index = 'YTD_group', columns = 'Volume_change_group', values = 'ticker', aggfunc="sum",fill_value = 0,margins = True, margins_name = 'Razem')

volumes.index.name = 'Stopy zwrotu (%)'
volumes.columns.name = 'Zmiana śr. wolumenu R:R (%)'

volumes
```

## Maks Obsunięcie

```{python}
ytd_groups = df.loc[(df['in_WIG'] == True) & (df['in_WIG140'] == False)].groupby(['YTD_group','Drawdown_group'], as_index= False)['ticker'].count().pivot_table(index = 'YTD_group', columns = 'Drawdown_group', values = 'ticker', aggfunc="sum",fill_value = 0,margins = True, margins_name = 'Razem')

ytd_groups.index.name = 'Stopy zwrotu (%)'
ytd_groups.columns.name = 'Maksymalne obsunięcie kursu (%)'

ytd_groups
```

## Kapitalizacje

```{python}
g = df.loc[(df['in_WIG'] == True) & (df['in_WIG140'] == False)].groupby('Market_cap_group')['ticker']

summary = g.count().to_frame('Liczba')
summary['Udział w całości (%)'] = round(g.count() / g.count().sum() * 100,2)

summary.index.name = 'Kapitalizacja na koniec 2025r'

summary
```
:::

Finalnie grupa spółek należących do indeksu WIG, z pominięciem walorów z WIG140 (a więc połączenia WIG20, mWIG40 i sWIG80). Tutaj wyznaczone przeze mnie przedziały stóp zwrotu reprezentowane są w sposób najbardziej równomierny - pośród 184 spółek znajdziemy zarówno te z zaliczonym spadkiem o ponad 30% (21 spółek), jak i te rosnące o ponad 60% (26 spółek). Spośród analizowanych w tej części spółek, wszystkie z TOP5 urosły w 2025 roku o ponad 200%. Liderem wzrostów został PASSUS (+257%). Warto tutaj także zwrócić uwagę jak różne drogi prowadziły do tych rezultatów. Z jednej strony spółki Passus i Atrem przez cały rok obsunęły się maksymalnie o 20 i 17%. Wolumen w przypadku pierwszego podmiotu uległ zwiększeniu o 361%, a drugiegoo 16%. Nieco mniejszą stopą zwrotu może pochwalić się Coalenergy (+241%), wynik ten osiągnięty stosunkowo dużym kosztem. O finalnym wyniku zdecydował mocny ruch w lutym, a w kolejnych okresach inwestorzy musieli liczyć się z istotnymi wahaniami kursu (obsunięcie maksymalne rzędu 67%), a to wszystko zostało potwierdzone wolumenem rosnącym o niemal 950% w stosunku do rezultatu z roku 2024.

Jeśli chodzi o największe spadki, aż 3 z 5 wykazanych miejsc należą do spółek z sektora ochrony zdrowia. Niemal 80% spadek zanotowało Pure Biologics. Należy tu jednak zaznaczyć, że pojawia się pewna rozbieżność w danych, w zależności od źródła. Zgodnie z wartościami podawanymi m.in. przez stooq, ta zmiana procentowa to 52%, zaś dane yahoo finance na którym bazuje niniejszy wpis są spójne z wartościami dostępnymi na stronie GPW i jasno wskazują na przecenę o 80%. 

Analizując średnie dzienne wolumeny i ich porównanie do poprzedniego roku, proporcje spółek z rosnącym i malejącym wyglądają podobnie jak w przypadku sWIG80. Jeśli jednak skupimy uwagę tylko na znacznych spadkach, o minimum 20%, wówczas WIG rest wypada gorzej - 28% analizowanych spółek versus 20% w sWIG80. Tendencja wygląda analogicznie w przypadku obsunięć kursów w trakcie roku. W przypadku aż 58% walorów inwestorzy musieli liczyć się nawet z 25-procentową lub większą przeceną. 

Oczywiście omawiany fragment indeksu to zestaw najmniejszych spółek na GPW. Niemal 84% notowanych podmiotów zakończyło rok 2025 z kapitalizacją poniżej 300 mln złotych. 

# Na zakończenie

Imponujące wzrosty w 2025, jakimi indeksy WIG20 (+45%), mWIG40 (+33%) i sWIG80 (+25%) prowadzą z łatwością do wizji gigantycznych wzrostów dostępnych na wyciągnięcie ręki, choć finalnie okazuje się, że chociażby w przypadku spółek sWIG80 czy WIG rest aż 40% podmiotów zakończyła rok ze spadkiem kursu. W przypadku indeksów GPW za tę magię odpowiadają wagi poszczególnych spółek. Przykładowo w WIG20 drugą i trzecią spółką względem wagi są PKN Orlen (13,131 udziału w portfelu) i KGHM (10,665), a więc walory które w całym WIG20 rosły w ubiegłym roku najmocniej. Z drugiej strony, jedyny outsider - CCC, którego kurs stracił 35%, ma w tym portfelu wagę 1,445%. 

Przyjmując zatem strategię selektywnego doboru spółek kosztem inwestycji w cały indeks, kluczem do osiągnięcia sukcesu było przede wszystkim zaangażowanie w spółki o jak największej skali działalności. Wydawać by się zatem mogło, że kwestia doboru branży w przypadku GPW zeszła nieco na drugi plan, jednak jest to błędne założenie, co wyjaśnia poniższy wykres:

```{python}
#| fig-height: 19

plt.figure(figsize=(10, 8)) 

cnt = (
    df.loc[df['in_WIG']]
      .groupby(['YTD_group', 'L1_nazwa'], as_index=False)['ticker']
      .count()
      .rename(columns={'ticker': 'count'})
)

cnt['pct_in_L1'] = (
    cnt['count'] /
    cnt.groupby('L1_nazwa')['count'].transform('sum') * 100
)

cnt.L1_nazwa.replace('Produkcja przemysłowa i budowlano-montażowa', 'Prod. przemysł. i bud-mont.', inplace= True)

ax = sns.heatmap(cnt[['YTD_group', 'L1_nazwa', 'pct_in_L1']].pivot(index = 'L1_nazwa',  columns = 'YTD_group', values = 'pct_in_L1'), fmt=".0f", annot=True, linewidths=0, cmap="YlGn", cbar = False)

plt.title('Rozkład stóp zwrotu spółek WIG w obrębie sektorów*', loc = 'center')
plt.xlabel('Stopa zwrotu w 2025 roku (%)')
plt.ylabel(None)
plt.text(x = 4, y = 9, s = "*wartości jako % spółek w danym sektorze")
ax.xaxis.tick_top()
ax.set_xticklabels(labels = ['<= -30%', '-30% - -15%', '-15% - 0', '0% - 20%', '20% - 60%', '>60%'], rotation=90, ha='right');
```

Stosując klasyfikację sektorową przyjętą przez GPW Benchmark i nakładając ją stopy zwrotu spółek z całego indeksu WIG, pogrupowane względem wielkości, doskonale widać, że istnieje spora grupa sektorów, których co najmniej 30% spółek wygenerowało wzrost 20-60% w ubiegłym roku. Są to: dobra konsumpcyjne, finanse, paliwa i energia, produkcja przemysłowa i budowlano montażowa oraz technologie. 

W przypadku czterech pozostałych sektorów, sytuacja ma się nieco inaczej. Spółki chemiczne i surowcowe skoncentrowały się w okół stóp zwrotu na poziomie 0-20% -> 42% całego sektora, co wciąż negatywnym zjawiskiem nie jest. Połowiczny sukces osiągnęły także spółki z sektora Paliwa i energia (po 25% spółek rosnących 20-60% i spadających -30 - -15%), natomiast dystrybucję spółek handlowych i usługowych można uznać za względnie równomiernie rozłożoną pomiędzy grupy stóp zwrotu. Największym przegranym 2025 roku jest natomiast sektor ochrony zdrowia obejmujący m.in. spółki biotechnologiczne i med-tech. W tym przypadku aż 71% walorów tego sektora straciła w trakcie ubiegłego roku. 

Pierwsze sesje 2026 roku napawają optymizmem dla całej GPW, niezależnie od wielkości spółek czy sektora. Predykcje co do bieżącego roku są przeważnie jednoznaczne i podkreśla się w nich większy potencjał u spółek małych oraz średnich. 